[package]
name = "keyproc"
version = "0.1.0"
edition = "2024"

[dependencies]
x25519-dalek = { version = "2", features = ["static_secrets","getrandom"] }
base64 = "0.22"
aes-gcm = "0.10.3"
serde_json = "1.0.145"
zeroize = "1.8.2"
